
POST http://localhost:3000/user/signup
content-type: application/json; charset=utf-8

{
  "email": "asda@gmail.com",
  "password": "Elegancko",
  "asd": "Sdasd"
}

###
GET http://localhost:3000/user/1
content-type: application/json; charset=utf-8

{
"email": "asda@gmail.com",
"password": "Elegancko",
"asd": "Sdasd"
}
###
PUT http://localhost:3000/user/1
content-type: application/json; charset=utf-8

{
  "email": "Alexander@gmail.com",
  "password": "Alexander",
  "asd": "Sdasd"
}