
POST http://localhost:3000/user/signup
content-type: application/json; charset=utf-8

{
  "email": "AleXander123@gmail.com",
  "password": "AleXander",
  "asd": "AleXander"
}

###
GET http://localhost:3000/user/1
content-type: application/json; charset=utf-8
####

GET http://localhost:3000/user
content-type: application/json; charset=utf-8
####

PATCH http://localhost:3000/user/1
content-type: application/json; charset=utf-8

{
  "email": "Jakub@gmail.com",
  "password": "Alexander"
}